### ISSUE TITLE
JSDocs

### ISSUE THREAD

**Issue by aikar** [scottcorgan/as-array#1]
@scottcorgan I know it's been ages since you've prob looked at this, but can you please add JSDocs to the method so its clear it returns an array?

This would help with IDE completion.

I at least fixed it locally by writing a Flow doc

```javascript
/** @flow */
declare module "as-array" {
    declare module.exports: (data: any) => any[];
}
```

**Comment by scottcorgan** [comment]
I’d love a PR. This is a create idea!

**Comment by scottcorgan** [comment]
Going to close this. We can continue conversation if you'd like though
